### ISSUE TITLE
没看明白怎么玩的，直接把项目下下来没有后台服务器呀

### ISSUE THREAD

**Issue by zhanghaifei1997** [opq-osc/panel#11]

**Comment by xiyaowong** [comment]
光下载不行，还得build。readme都不看？

**Comment by zhanghaifei1997** [comment]
> 光下载不行，还得build。readme都不看？

可能是因为我没有搭配别的程序启动的原因吧，毕竟打包过后还得放到服务器上啥的运行吧

**Comment by xiyaowong** [comment]
放在opq对应的WebUi文件夹就可以了   
WebUi/index.html

**Comment by zhanghaifei1997** [comment]
> 放在opq对应的WebUi文件夹就可以了   
> 
> WebUi/index.html

了解明白马上就试试

**Comment by Teeoo** [comment]
好家伙你们搁这儿聊天呢
